#Arrays


In [ ]:
import numpy as np

In [ ]:
#array creation
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#array generation
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros((6,6))#rows,columns
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,3)#give me elements between 1 to 5 with linear space of 3
arr

array([1., 3., 5.])

In [ ]:
#random generation
np.random.rand(10)#standardised values

array([0.46427397, 0.44479059, 0.1805989 , 0.16417911, 0.79464227,
       0.97573611, 0.72178501, 0.74376945, 0.98729806, 0.51794831])

In [ ]:
np.random.randn(10)#normalised values

array([-0.68222549,  0.20185436,  1.35945519, -0.59581782, -1.36268959,
       -0.68634503, -1.20531111,  0.13046641, -1.64162456,  0.44479427])

In [ ]:
np.random.randint(6,10,10)

array([6, 7, 7, 8, 8, 8, 8, 6, 6, 9])

In [ ]:
#array attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#methods
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0) #row-wise 1 column-wise 0

array([12, 15, 18])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()#index of max

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
#reshaping and resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)#the size must fit all elements

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

#Indexing and Slicing


In [ ]:
import numpy as np
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[8]

np.int64(19)

In [ ]:
arr[1:5]#end in excluded

array([12, 13, 14, 15])

In [ ]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3:8:2]

array([14, 16, 18])

In [ ]:
#numpy indexing and slicing
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0,1] #rows , columns

np.int64(2)

In [ ]:
arr[0:2,1:3] #rows columns

array([[2, 3],
       [7, 8]])

In [ ]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
#boolean indexing
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

#Array Operations

In [ ]:
#array operations
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2 #size must be same

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
#broadcasting
l = [10,20,30,40,50]
arr = np.array(l)

In [ ]:
arr + 10 # adding 10 in every element

array([20, 30, 40, 50, 60])

In [ ]:
#deep and shallow copy
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice * 10 # --> changes made on shallow copy so changes will not affect main array

array([10, 20, 30, 40, 50])

In [ ]:
a
#b = a # deep copy affects main array as well
b = a.copy() #creates shallow copy

In [ ]:
b[1] = 90

In [ ]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#matrix operations
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A * B #not matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [ ]:
A @ B #matrix multiplications

array([[19, 22],
       [43, 50]])

In [ ]:
A.T #transpose

array([[1, 3],
       [2, 4]])

In [ ]:
#stacking array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#splitting arrays
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

#exercises

In [ ]:
#valid sudoku
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
#valid sudoku
b = np.sum(s,axis=1)
for i in b:
  if i != 45:
    print("invalid")
    break
else:
  print("valid")

valid


In [ ]:
c = np.sum(s,axis=1)

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n = s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
#Get the shape of the matrix.
#Find the average age of students.
#Extract Math marks of all students.
#Find the highest Science mark.
#Get details of the student who scored more than 90 in Math.
#Increase Math marks of all students by 5.
#Find how many students are younger than 19.
#Calculate the average marks in each subject (column-wise mean).
#Get data of students who scored at least 80 in both subjects.
#Replace all Science marks < 75 with 0.

In [ ]:
#shape
data.shape

(5, 3)

In [ ]:
#average age
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
#maths mraks
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
#highest science marks
np.max(data[:,2])

np.int64(95)

In [ ]:
#more than 90 in maths
data[data[:,1]>=90]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#adding 10
data[:,1]+5

array([90, 97, 81, 70, 95])

In [ ]:
data[data[:,0]<19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [ ]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [ ]:
data[(data[:,1] >=80) & (data[:,2] >=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
 data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
data[:,2][data[:,2]<75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])